// packages/ui/src/components/react/input/input.tsx
import * as React from "react";
import { cn } from "@repo/utils";
import { inputClasses } from "../../../shared/variants/input";

export interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, type, ...props }, ref) => {
    return (
      <input
        type={type}
        className={cn(inputClasses.base, className)}
        ref={ref}
        {...props}
      />
    );
  },
);
Input.displayName = "Input";

export { Input };

// packages/ui/src/components/solid/input/input.tsx
import { splitProps, JSX, Component } from "solid-js";
import { cn } from "@repo/utils";
import { inputClasses } from "../../../shared/variants/input";

export interface InputProps extends JSX.InputHTMLAttributes<HTMLInputElement> {}

export const Input: Component<InputProps> = (props) => {
  const [local, others] = splitProps(props, ["class", "type"]);

  return (
    <input
      type={local.type ?? "text"}
      class={cn(inputClasses.base, local.class)}
      {...others}
    />
  );
};
