// apps/app-solidjs/src/entry-mfe.tsx
import { render } from "solid-js/web";
import App from "./App";
import "./index.css";
import { AppRegistry, createSolidMfeEntry } from "@repo/core/solid";
import { APP_IDS } from "@repo/config";

const {
  mount,
  unmount,
  default: microApp,
} = createSolidMfeEntry({
  AppComponent: App,
  appId: APP_IDS.SOLIDJS,
  registry: AppRegistry,
  render,
});

export { mount, unmount };
export default microApp;

// apps/app-react/src/entry-mfe.tsx
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "@repo/ui/globals.css";
import { AppRegistry, createReactMfeEntry } from "@repo/core/react";
import { APP_IDS } from "@repo/config";

const {
  mount,
  unmount,
  default: microApp,
} = createReactMfeEntry({
  AppComponent: App,
  appId: APP_IDS.REACT,
  registry: AppRegistry,
  StrictMode: React.StrictMode,
  createRoot: ReactDOM.createRoot,
});

export { mount, unmount };
export default microApp;
