// packages/ui/src/components/solid/card/card.tsx
import { splitProps, JSX, Component, mergeProps } from "solid-js";
import { cn } from "@repo/utils";
import { cardClasses } from "../../../shared/variants/card";

export interface CardProps extends JSX.HTMLAttributes<HTMLDivElement> {
  gradient?: boolean;
}

export const Card: Component<CardProps> = (props) => {
  const merged = mergeProps({ gradient: false }, props);
  const [local, others] = splitProps(merged, ["gradient", "class", "children"]);

  return (
    <div
      class={cn(
        cardClasses.root,
        local.gradient && cardClasses.rootGradient,
        local.class,
      )}
      {...others}
    >
      {local.children}
    </div>
  );
};

export const CardHeader: Component<JSX.HTMLAttributes<HTMLDivElement>> = (
  props,
) => {
  const [local, others] = splitProps(props, ["class", "children"]);
  return (
    <div class={cn(cardClasses.header, local.class)} {...others}>
      {local.children}
    </div>
  );
};

export const CardTitle: Component<JSX.HTMLAttributes<HTMLHeadingElement>> = (
  props,
) => {
  const [local, others] = splitProps(props, ["class", "children"]);
  return (
    <h3 class={cn(cardClasses.title, local.class)} {...others}>
      {local.children}
    </h3>
  );
};

export const CardDescription: Component<
  JSX.HTMLAttributes<HTMLParagraphElement>
> = (props) => {
  const [local, others] = splitProps(props, ["class", "children"]);
  return (
    <p class={cn(cardClasses.description, local.class)} {...others}>
      {local.children}
    </p>
  );
};

export const CardContent: Component<JSX.HTMLAttributes<HTMLDivElement>> = (
  props,
) => {
  const [local, others] = splitProps(props, ["class", "children"]);
  return (
    <div class={cn(cardClasses.content, local.class)} {...others}>
      {local.children}
    </div>
  );
};

export const CardFooter: Component<JSX.HTMLAttributes<HTMLDivElement>> = (
  props,
) => {
  const [local, others] = splitProps(props, ["class", "children"]);
  return (
    <div class={cn(cardClasses.footer, local.class)} {...others}>
      {local.children}
    </div>
  );
};

// packages/ui/src/components/react/card/card.tsx
import * as React from "react";
import { cn } from "@repo/utils";
import { cardClasses } from "../../../shared/variants/card";

export interface CardProps extends React.HTMLAttributes<HTMLDivElement> {
  gradient?: boolean;
}

export const Card = React.forwardRef<HTMLDivElement, CardProps>(
  ({ className, gradient, ...props }, ref) => (
    <div
      ref={ref}
      className={cn(
        cardClasses.root,
        gradient && cardClasses.rootGradient,
        className,
      )}
      {...props}
    />
  ),
);
Card.displayName = "Card";

export const CardHeader = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div ref={ref} className={cn(cardClasses.header, className)} {...props} />
));
CardHeader.displayName = "CardHeader";

export const CardTitle = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLHeadingElement>
>(({ className, ...props }, ref) => (
  <h3 ref={ref} className={cn(cardClasses.title, className)} {...props} />
));
CardTitle.displayName = "CardTitle";

export const CardDescription = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLParagraphElement>
>(({ className, ...props }, ref) => (
  <p ref={ref} className={cn(cardClasses.description, className)} {...props} />
));
CardDescription.displayName = "CardDescription";

export const CardContent = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div ref={ref} className={cn(cardClasses.content, className)} {...props} />
));
CardContent.displayName = "CardContent";

export const CardFooter = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div ref={ref} className={cn(cardClasses.footer, className)} {...props} />
));
CardFooter.displayName = "CardFooter";
