// packages/ui/src/components/vue/input/Input.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "@repo/utils";
import { inputClasses } from "../../../shared/variants/input";

interface InputProps {
  modelValue?: string | number;
  class?: string;
  type?: string;
  placeholder?: string;
  disabled?: boolean;
}

const props = withDefaults(defineProps<InputProps>(), {
  type: "text",
  disabled: false,
});

const emit = defineEmits<{
  "update:modelValue": [value: string];
}>();

const classes = computed(() => cn(inputClasses.base, props.class));

function handleInput(event: Event) {
  const target = event.target as HTMLInputElement;
  emit("update:modelValue", target.value);
}
</script>

<template>
  <input
    :type="type"
    :class="classes"
    :value="modelValue"
    :placeholder="placeholder"
    :disabled="disabled"
    @input="handleInput"
  />
</template>

// packages/ui/src/components/svelte/input/Input.svelte
<script lang="ts">
  import { cn } from "@repo/utils";
  import { inputClasses } from "../../../shared/variants/input";

  export let value = "";
  export let placeholder = "";
  export let disabled = false;
  let className = "";
  export { className as class };

  $: classes = cn(inputClasses.base, className);
  
  function handleInput(e: Event) {
    value = (e.target as HTMLInputElement).value;
  }
</script>

<input
  type="text"
  class={classes}
  {value}
  {placeholder}
  {disabled}
  on:input={handleInput}
  on:change
  on:focus
  on:blur
/>
