// packages/ui/src/components/svelte/card/Card.svelte
<script lang="ts">
  import { cn } from "@repo/utils";
  import { cardClasses } from "../../../shared/variants/card";

  export let gradient = false;
  let className = "";
  export { className as class };

  $: classes = cn(cardClasses.root, gradient && cardClasses.rootGradient, className);
</script>

<div class={classes}>
  <slot />
</div>

// packages/ui/src/components/vue/card/Card.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "@repo/utils";
import { cardClasses } from "../../../shared/variants/card";

interface CardProps {
  class?: string;
  gradient?: boolean;
}

const props = withDefaults(defineProps<CardProps>(), {
  gradient: false,
});

const classes = computed(() =>
  cn(cardClasses.root, props.gradient && cardClasses.rootGradient, props.class)
);
</script>

<template>
  <div :class="classes">
    <slot />
  </div>
</template>
